### ISSUE TITLE
1.0.0 Crashing when tilling

### ISSUE THREAD

**Issue by Cordova19** [Theoness1/vanilla-claws#1]
I've accidentally crashed my game a few times and I've managed to replicate it by trying to till using the claws.
[crash-2022-08-03_14.25.21-client.txt](https://github.com/Theoness1/vanilla-claws/files/9255416/crash-2022-08-03_14.25.21-client.txt)

**Comment by Theoness1** [comment]
Did the crash happen when you digging leaves or earth?

**Comment by Theoness1** [comment]
Always failing when tillage?

**Comment by PinkGoosik** [comment]
That's a weird one, is it crashes all the time or in some certain context?

**Comment by Cordova19** [comment]
Context didn't seem to matter much, tried tilling with a claw first thing in a new world and it still crashed.

**Comment by Theoness1** [comment]
I tested, all works. Maybe my mod conflict with other

**Comment by Cordova19** [comment]
Yup, tried the mod by itself and plowing worked just fine. Seems to be a mod conflict.

**Comment by Theoness1** [comment]
send mod list

**Comment by Cordova19** [comment]
[Cordovadammandant (1).zip](https://github.com/Theoness1/vanilla-claws/files/9266288/Cordovadammandant.1.zip)
 Just figured out the whole Curseforge Export thing, hope this will do

**Comment by Theoness1** [comment]
send screenshot pls xd

**Comment by Cordova19** [comment]
![Screenshot](https://user-images.githubusercontent.com/97481409/183023966-4c5b6458-783f-465f-a206-002a52f90f17.png)
Sure thing

**Comment by Theoness1** [comment]
Maybe it's some tool mod conflicting with claws

**Comment by Cordova19** [comment]
Finally figured it out! "Levelz" is the conflict. No clue why, but after a lot of testing it started working again after I disabled Levelz.
